chore: pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -18,3 +18,9 @@ if [ $? -ne 0 ]; then
   echo "Prettier check failed. Commit aborted."
   exit 1
 fi
+
+tsc --noEmit
+if [ $? -ne 0 ]; then
+  echo "Type check failed. Commit aborted."
+  exit 1
+fi
